"""add_display_name_to_audio_files

Revision ID: 6e59e4297f50
Revises: d5a9f6dff98f
Create Date: 2025-06-20 18:44:40.841568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e59e4297f50'
down_revision = 'd5a9f6dff98f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'display_name')
    # ### end Alembic commands ### 