"""add_stt_config_table

Revision ID: 79b756b31539
Revises: 8f8ddd142d70
Create Date: 2025-06-20 09:49:16.817998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b756b31539'
down_revision = '8f8ddd142d70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stt_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('speaker_diarization', sa.Boolean(), nullable=True),
    sa.Column('speaker_names', sa.JSON(), nullable=True),
    sa.Column('profanity_filter', sa.Boolean(), nullable=True),
    sa.Column('noise_reduction', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stt_configs_id'), 'stt_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stt_configs_id'), table_name='stt_configs')
    op.drop_table('stt_configs')
    # ### end Alembic commands ### 