"""update_stt_config_and_transcript_models

Revision ID: 8ce2387596e8
Revises: 79b756b31539
Create Date: 2025-06-20 09:55:38.962395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ce2387596e8'
down_revision = '79b756b31539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stt_configs', sa.Column('spk_count', sa.Integer(), nullable=True))
    op.drop_column('stt_configs', 'speaker_names')
    op.add_column('transcripts', sa.Column('speaker_labels', sa.JSON(), nullable=True))
    op.add_column('transcripts', sa.Column('speaker_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'speaker_names')
    op.drop_column('transcripts', 'speaker_labels')
    op.add_column('stt_configs', sa.Column('speaker_names', mysql.JSON(), nullable=True))
    op.drop_column('stt_configs', 'spk_count')
    # ### end Alembic commands ### 