"""add_report_entities

Revision ID: 8f8ddd142d70
Revises: 002
Create Date: 2025-06-20 07:29:40.279346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '8f8ddd142d70'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('published_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('canva_design_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_reports_id'), 'published_reports', ['id'], unique=False)
    op.create_table('report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_data_id'), 'report_data', ['id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.add_column('audio_files', sa.Column('report_id', sa.Integer(), nullable=False))
    op.add_column('audio_files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('audio_files', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('audio_files', sa.Column('upload_status', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'audio_files', 'reports', ['report_id'], ['id'])
    op.drop_column('audio_files', 'stt_transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('stt_transcript', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'audio_files', type_='foreignkey')
    op.drop_column('audio_files', 'upload_status')
    op.drop_column('audio_files', 'duration')
    op.drop_column('audio_files', 'file_size')
    op.drop_column('audio_files', 'report_id')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_report_data_id'), table_name='report_data')
    op.drop_table('report_data')
    op.drop_index(op.f('ix_published_reports_id'), table_name='published_reports')
    op.drop_table('published_reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    # ### end Alembic commands ###