"""add_new_stt_config_fields

Revision ID: b4c727e68dfc
Revises: dc3e98f17f7c
Create Date: 2025-06-20 10:02:11.920645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c727e68dfc'
down_revision = 'dc3e98f17f7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stt_configs', sa.Column('language_candidates', sa.JSON(), nullable=True))
    op.add_column('stt_configs', sa.Column('use_paragraph_splitter', sa.Boolean(), nullable=True))
    op.add_column('stt_configs', sa.Column('paragraph_max_length', sa.Integer(), nullable=True))
    op.add_column('stt_configs', sa.Column('domain', sa.String(length=20), nullable=True))
    op.add_column('stt_configs', sa.Column('use_word_timestamp', sa.Boolean(), nullable=True))
    op.add_column('stt_configs', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stt_configs', 'keywords')
    op.drop_column('stt_configs', 'use_word_timestamp')
    op.drop_column('stt_configs', 'domain')
    op.drop_column('stt_configs', 'paragraph_max_length')
    op.drop_column('stt_configs', 'use_paragraph_splitter')
    op.drop_column('stt_configs', 'language_candidates')
    # ### end Alembic commands ### 