"""update_stt_config_add_disfluency_remove_word_timestamp

Revision ID: d5a9f6dff98f
Revises: b4c727e68dfc
Create Date: 2025-06-20 18:20:20.202135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5a9f6dff98f'
down_revision = 'b4c727e68dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stt_configs', sa.Column('use_disfluency_filter', sa.Boolean(), nullable=True))
    op.drop_column('stt_configs', 'use_word_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stt_configs', sa.Column('use_word_timestamp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('stt_configs', 'use_disfluency_filter')
    # ### end Alembic commands ### 