"""remove_noise_reduction_from_stt_config

Revision ID: dc3e98f17f7c
Revises: 8ce2387596e8
Create Date: 2025-06-20 09:58:43.315193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3e98f17f7c'
down_revision = '8ce2387596e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stt_configs', 'noise_reduction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stt_configs', sa.Column('noise_reduction', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 